version: '3'

services:

  nginx:
    container_name: debug-nginx
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - php-fpm
    volumes:
      - ./app/:/var/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf


  php-fpm:
    container_name: debug-php-fpm
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    expose:
      - "9000"
    volumes:
      - ./app/:/var/www/public
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
#      - ./docker/php/xdebug.ini:/etc/php/7.4/mods-available/xdebug.ini